[grid]
size=256 # Grid size
length=0.6 # Grid length

[turbulence]
Cn2=1e-14 # Refractive index structure constant
L0=10.0 # Outer scale of turbulence
l0=0 # Inner scale of turbulence

[beam]
wavelength=633e-9
waist=0.15

[simulation]
propagation_distance=800
magnification=1
nsteps=1
batchsize=128
nbatches=8